version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: botDiscordV14
    environment:
      MYSQL_ROOT_PASSWORD: senhaRoot
      MYSQL_DATABASE: botDiscordV14-DB
      MYSQL_USER: usuario
      MYSQL_PASSWORD: 40028922
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: